; OpenRC AeroLink — ESP32 FC com MinimOSD + SiK telemetry
;
; Compile com: pio run
; Upload com:  pio run -t upload
; Monitor com: pio device monitor -b 115200

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D MAVLINK_COMM_NUM_BUFFERS=3
    -I src
    -I lib/mavlink

lib_deps =
    nrf24/RF24@^1.4.10
    madhephaestus/ESP32Servo@^3.0.5
    adafruit/Adafruit MPU6050@^2.2.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    br3ttb/PID@^1.2.1
    bblanchon/ArduinoJson@^7.0.4
    mikalhart/TinyGPSPlus@^1.0.3
    ; adafruit/Adafruit BMP280 Library@^2.6.8   ; descomentar quando comprar baro

; MAVLink c_library_v2 vai em lib/mavlink/ (apenas headers, sem .lib_deps).
; Clone:
;   git clone --recursive https://github.com/mavlink/c_library_v2 lib/mavlink
